import { useState } from 'react'
import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, Compass, FileText, PawPrint } from 'lucide-react'

type Resource = { title: string; body: string; category: string; source: string; sourceUrl: string; sourceType: string; takeaway: string }
const resources: Resource[] = [
  { title: 'Start with a close physical search', body: 'A peer-reviewed study of missing cats found that physical searching was associated with recovering cats alive. Useful tactics included searching the yard and immediate area, walking the neighborhood, calling the cat, and speaking with neighbors.', category: 'Searching', source: 'Huang et al., Animals (2018)', sourceUrl: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5789300/', sourceType: 'Peer-reviewed study', takeaway: 'Search nearby spaces physically before assuming a long-distance move.' },
  { title: 'Indoor-only cats are often closer', body: 'The same study concluded that a search within a 200-meter radius is more likely to be sufficient for an indoor-only cat, while outdoor-access cats may require a search extending to 2 kilometers or more.', category: 'Behavior', source: 'Huang et al., Animals (2018)', sourceUrl: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5789300/', sourceType: 'Peer-reviewed study', takeaway: 'Match the first search radius to the cat’s outdoor experience.' },
  { title: 'Inspect concealment, not just open space', body: 'Cats in the study commonly escaped into environments with many hiding places, including shrubbery, vehicles, decks, porches, and sheds. Cats found outside were frequently hiding under porches, cars, or objects near home.', category: 'Searching', source: 'Huang et al., Animals (2018)', sourceUrl: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5789300/', sourceType: 'Peer-reviewed study', takeaway: 'Use a flashlight and inspect beneath and behind objects carefully.' },
  { title: 'A frightened cat may stay silent', body: 'Missing Animal Response Network explains that displaced indoor-only cats may hide silently in unfamiliar territory and may not meow, even when they recognize a familiar voice.', category: 'Behavior', source: 'Missing Animal Response Network', sourceUrl: 'https://www.missinganimalresponse.com/lost-cat-behavior/', sourceType: 'Specialist guidance', takeaway: 'Silence does not mean your cat is far away or cannot hear you.' },
  { title: 'Ask neighbors to check enclosed spaces', body: 'The ASPCA recommends asking neighbors to check garages and sheds, and the missing-cat study found that speaking with neighbors and asking them to look or assist was among the useful physical-search strategies.', category: 'Outreach', source: 'ASPCA: Finding a Lost Pet', sourceUrl: 'https://www.aspca.org/pet-care/general-pet-care/finding-lost-pet', sourceType: 'Animal welfare guidance', takeaway: 'Ask for a physical inspection before garages or sheds are closed again.' },
  { title: 'Use identification and widen outreach', body: 'ASPCA guidance recommends contacting local shelters and animal-control agencies, distributing flyers, posting online, and ensuring pets wear current ID tags. ASPCA also notes microchips as an important safeguard for lost cats.', category: 'Outreach', source: 'ASPCA: Finding a Lost Pet', sourceUrl: 'https://www.aspca.org/pet-care/general-pet-care/finding-lost-pet', sourceType: 'Animal welfare guidance', takeaway: 'Pair a physical search with shelters, flyers, online posts, and current identification.' }
  ,{ title: 'Repeat searches at different times', body: 'Best Friends Animal Society recommends repeatedly searching inside and outside the property and varying search times. A cat can move from an original hiding place into an area that seemed clear earlier.', category: 'Searching', source: 'Best Friends Animal Society', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-find-lost-cat-tips-pet-detective', sourceType: 'Animal welfare guidance', takeaway: 'Re-check the same ground slowly, including late-night and early-morning quiet hours.' }
  ,{ title: 'Check the home again', body: 'Best Friends notes that a missing cat can still be inside the house and recommends carefully checking cupboards, beneath mattresses, behind dressers, and other unlikely spaces more than once.', category: 'Searching', source: 'Best Friends Animal Society', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-find-lost-cat-tips-pet-detective', sourceType: 'Animal welfare guidance', takeaway: 'If an escape was not witnessed, treat a thorough indoor re-check as a real search step.' }
  ,{ title: 'Use humane traps responsibly', body: 'Best Friends recommends humane traps as one part of an active search and notes that shelters may rent them to the public. Any trap should be placed where it can be checked frequently.', category: 'Recovery', source: 'Best Friends Animal Society', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-find-lost-cat-tips-pet-detective', sourceType: 'Animal welfare guidance', takeaway: 'Use a monitored humane trap as a supplement to physical searching, not a replacement.' }
  ,{ title: 'Make flyers easy to notice', body: 'ASPCA recommends a large readable headline, a recent photo, identifying details, last-seen information, and two contact numbers. A consistent design helps repeated viewings stick in people’s minds.', category: 'Outreach', source: 'ASPCA: Finding a Lost Pet', sourceUrl: 'https://www.aspca.org/pet-care/finding-lost-pet', sourceType: 'Animal welfare guidance', takeaway: 'Keep flyers bold, legible at a distance, and visually consistent.' }
  ,{ title: 'Check shelters repeatedly', body: 'ASPCA recommends contacting animal-control agencies, veterinary hospitals, shelters, and rescue groups, then checking shelters daily and visiting in person with photos when possible.', category: 'Outreach', source: 'ASPCA: Finding a Lost Pet', sourceUrl: 'https://www.aspca.org/pet-care/finding-lost-pet', sourceType: 'Animal welfare guidance', takeaway: 'Do not assume one phone call or one shelter covers the full area.' }
  ,{ title: 'If you find a roaming cat', body: 'Best Friends recommends knocking on nearby doors, contacting shelters and veterinarians, posting found-pet flyers, and asking a shelter or veterinary office to scan the animal for a microchip.', category: 'Sightings', source: 'Best Friends Animal Society', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-care-stray-or-lost-pet', sourceType: 'Animal welfare guidance', takeaway: 'Report the sighting and seek guidance before moving or containing an unfamiliar cat.' }
  ,{ title: 'Keep microchip records current', body: 'The ASPCA notes that microchips are only as useful as the information registered with the chip company. If a phone number or address changes, update the record promptly.', category: 'Prevention', source: 'ASPCA: Finding a Lost Pet', sourceUrl: 'https://www.aspca.org/pet-care/finding-lost-pet', sourceType: 'Animal welfare guidance', takeaway: 'Confirm the registry has your current contact details before an emergency happens.' }
  ,{ title: 'Understand what a microchip can do', body: 'AVMA guidance explains that a microchip contains a unique identification number. It helps identify a found animal when scanned, but it is not a GPS tracking device.', category: 'Prevention', source: 'American Veterinary Medical Association', sourceUrl: 'https://ebusiness.avma.org/files/productdownloads/mcm-client-brochures-microchips-2022.pdf', sourceType: 'Veterinary guidance', takeaway: 'Use a microchip for permanent identification, not real-time location tracking.' }
  ,{ title: 'Prepare for fireworks and loud noises', body: 'ASPCA survey findings reported that nearly one in five lost pets went missing after fireworks, thunderstorms, or other loud noises. A personalized plan and current pet records help people act quickly.', category: 'Prevention', source: 'ASPCA: Fireworks and Lost Pets', sourceUrl: 'https://www.aspca.org/about-us/press-releases/what-if-your-pet-goes-missing-during-4th-july-fireworks-theres-app', sourceType: 'Animal welfare guidance', takeaway: 'Before predictable noise events, verify doors, identification, photos, and contact details.' }
  ,{ title: 'Monitor traps continuously', body: 'Best Friends trap guidance says not to leave humane traps unattended in an unprotected area because trapped animals are vulnerable. Weather protection and frequent checks are essential.', category: 'Recovery', source: 'Best Friends: Humane Cat Traps', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-use-humane-cat-traps-tnvr', sourceType: 'Animal welfare guidance', takeaway: 'Never set a trap and walk away. Keep the animal protected and respond quickly.' }
  ,{ title: 'Place traps where cats already travel', body: 'Best Friends recommends putting humane traps where cats usually feed or have been seen, using a level surface, and accounting for heat, rain, and other weather risks.', category: 'Recovery', source: 'Best Friends: Humane Cat Traps', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-use-humane-cat-traps-tnvr', sourceType: 'Animal welfare guidance', takeaway: 'Use sighting patterns to place a monitored trap in a stable, sheltered location.' }
  ,{ title: 'Ask community-cat caregivers', body: 'Best Friends notes that missing pet cats may join nearby groups of community cats. People who feed outdoor cats can notice a new arrival and provide useful sighting information.', category: 'Outreach', source: 'Best Friends Animal Society', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-find-lost-cat-tips-pet-detective', sourceType: 'Animal welfare guidance', takeaway: 'Include colony caregivers and regular outdoor feeders in neighborhood outreach.' }
  ,{ title: 'Check every shelter serving the area', body: 'Best Friends recommends checking all shelters that serve your area, not only the closest facility. ASPCA guidance similarly recommends contacting animal-control agencies, shelters, rescue groups, and veterinary hospitals.', category: 'Outreach', source: 'Best Friends Animal Society', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-find-lost-cat-tips-pet-detective', sourceType: 'Animal welfare guidance', takeaway: 'Build a contact list for the full service area and repeat your checks.' }
  ,{ title: 'Use social posts alongside physical outreach', body: 'ASPCA recommends sharing missing-pet information with local contacts and social networks, including local lost-pet pages. Online visibility works best alongside flyers and direct neighborhood searching.', category: 'Outreach', source: 'ASPCA: Finding a Lost Pet', sourceUrl: 'https://www.aspca.org/pet-care/finding-lost-pet', sourceType: 'Animal welfare guidance', takeaway: 'Post online quickly, but do not let online posting replace ground-level searching.' }
  ,{ title: 'Handle a found cat with care', body: 'Best Friends recommends contacting shelters and veterinarians, checking for a microchip, and seeking medical attention when a stray animal appears sick, injured, or aggressive.', category: 'Sightings', source: 'Best Friends Animal Society', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-care-stray-or-lost-pet', sourceType: 'Animal welfare guidance', takeaway: 'Prioritize safety and professional guidance when a found cat needs containment or care.' }
  ,{ title: 'Look for an ear tip', body: 'Best Friends trap guidance recommends checking whether a captured cat has an ear tip, a common sign that a community cat has already been spayed or neutered through a return program.', category: 'Sightings', source: 'Best Friends: Humane Cat Traps', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-use-humane-cat-traps-tnvr', sourceType: 'Animal welfare guidance', takeaway: 'An ear tip can help distinguish a managed community cat from the animal you are seeking.' }
  ,{ title: 'Do not stop too early', body: 'Best Friends cites documented reunions after extended periods and advises people not to give up. Search methods should be repeated, and outreach should continue as the search area expands.', category: 'Searching', source: 'Best Friends Animal Society', sourceUrl: 'https://bestfriends.org/pet-care-resources/how-find-lost-cat-tips-pet-detective', sourceType: 'Animal welfare guidance', takeaway: 'Keep a search log, revisit likely locations, and maintain outreach over time.' }
  ,{ title: 'Use a checklist during an emergency', body: 'ASPCA described a personalized recovery kit with step-by-step instructions based on a pet’s behavior and circumstances. Structured guidance can help people cover important tasks during a stressful search.', category: 'Planning', source: 'ASPCA: Missing Pet Kit', sourceUrl: 'https://www.aspca.org/about-us/press-releases/what-if-your-pet-goes-missing-during-4th-july-fireworks-theres-app', sourceType: 'Animal welfare guidance', takeaway: 'Track completed tasks and next actions so urgent details are not overlooked.' }
  ,{ title: 'Search again after dark', body: 'American Humane Society recommends searching at night with a flashlight because a lost pet may hide during the day. Pet FBI similarly notes that reflected eyes can make hidden cats easier to spot after dark.', category: 'Searching', source: 'American Humane Society', sourceUrl: 'https://www.americanhumane.org/public-education/what-to-if-youve-lost-your-pet/', sourceType: 'Animal welfare guidance', takeaway: 'Repeat the close search at night with a flashlight and pause often to listen.' }
  ,{ title: 'Ask permission to search yards yourself', body: 'Pet FBI says simply asking neighbors to look is often not enough. With permission, search likely hiding places in nearby yards physically, including spaces beneath decks, houses, and objects.', category: 'Searching', source: 'Pet FBI: Lost Cat Behavior', sourceUrl: 'https://petfbi.org/what-to-do/lost-cat-behavior/', sourceType: 'Lost-pet recovery guidance', takeaway: 'Request permission for a careful physical search instead of relying only on a verbal check.' }
  ,{ title: 'Check trees, rooftops, and vehicles', body: 'Pet FBI advises searching trees and rooftops as well as dark recesses. It also notes that curious cats may climb into vehicles or pickup trucks and be transported away accidentally.', category: 'Searching', source: 'Pet FBI: Lost Cat Action Plan', sourceUrl: 'https://petfbi.org/i-lost-a-cat/lost-cat-action-plan/index.html', sourceType: 'Lost-pet recovery guidance', takeaway: 'Scan both above and below ground level, and ask about vehicle activity near the escape time.' }
  ,{ title: 'Inspect construction sites carefully', body: 'Pet FBI identifies construction sites alongside garages and sheds as places where cats can become trapped. Searchers should get permission and avoid entering unsafe areas themselves.', category: 'Safety', source: 'Pet FBI: Lost Cat Action Plan', sourceUrl: 'https://petfbi.org/i-lost-a-cat/lost-cat-action-plan/index.html', sourceType: 'Lost-pet recovery guidance', takeaway: 'Ask the property owner or site manager to inspect equipment and materials safely.' }
  ,{ title: 'Try a camera and feeding station', body: 'Pet FBI describes wildlife cameras combined with feeding stations as a useful technique when a cat may be nearby but is hard to distinguish from other animals or difficult to trap.', category: 'Recovery', source: 'Pet FBI: Lost Cat Behavior', sourceUrl: 'https://petfbi.org/what-to-do/lost-cat-behavior/', sourceType: 'Lost-pet recovery guidance', takeaway: 'Use a camera to confirm visits and timing before choosing the next recovery step.' }
  ,{ title: 'Use familiar scent thoughtfully', body: 'Pet FBI recommends placing familiar items such as a favorite bed, blanket, or cat tree outside and, when safe, making a quiet route back inside available. Fragrant food can also help attract a nearby cat.', category: 'Recovery', source: 'Pet FBI: Steps to Find Your Lost Cat', sourceUrl: 'https://petfbi.org/assets/docs/Steps-to-find-your-lost-cat.pdf', sourceType: 'Lost-pet recovery guidance', takeaway: 'Create a calm, familiar return point and monitor it for activity.' }
  ,{ title: 'Keep calls calm and familiar', body: 'Pet FBI recommends using a normal speaking voice, pausing to listen, and trying familiar sounds such as a food bag or treat container. A frightened or injured cat may hide instead of approaching.', category: 'Searching', source: 'Pet FBI: Lost Cat Action Plan', sourceUrl: 'https://petfbi.org/i-lost-a-cat/lost-cat-action-plan/index.html', sourceType: 'Lost-pet recovery guidance', takeaway: 'Avoid loud continuous calling. Use familiar sounds, then stop and listen.' }
  ,{ title: 'Distribute flyers lawfully', body: 'Pet FBI recommends bright, legible flyers and community participation, while warning people not to post on utility poles or private property without permission and not to put non-mail items in mailboxes.', category: 'Outreach', source: 'Pet FBI: Lost Cat Action Plan', sourceUrl: 'https://petfbi.org/i-lost-a-cat/lost-cat-action-plan/index.html', sourceType: 'Lost-pet recovery guidance', takeaway: 'Use high-visibility locations, ask permission, and follow local posting rules.' }
  ,{ title: 'Alert TNR groups and colony caregivers', body: 'Pet FBI notes that community-cat caretakers and Trap-Neuter-Return groups may notice a newcomer at a feeding station. A flyer with a photo and contact details gives them something concrete to watch for.', category: 'Outreach', source: 'Pet FBI: Community Cat Caretakers', sourceUrl: 'https://petfbi.org/community-cat-caretakers-can-be-a-lost-cat-resource/', sourceType: 'Lost-pet recovery guidance', takeaway: 'Search for local TNR groups and share a clear photo with regular feeders.' }
  ,{ title: 'Watch for lost-pet scams', body: 'Pet FBI warns that scammers may impersonate shelters or animal-control officers and demand immediate payment before a reunion. Verify claims directly with the organization using an independently sourced phone number.', category: 'Safety', source: 'Pet FBI: Lost Pet Scams', sourceUrl: 'https://petfbi.org/lost-pet-scams/', sourceType: 'Lost-pet recovery guidance', takeaway: 'Do not send money or codes before independently verifying a sighting or custody claim.' }
  ,{ title: 'Use tags and a registered microchip', body: 'AVMA preparedness guidance recommends identification such as a collar tag and a registered microchip with current contact details. Multiple forms of identification improve the chance of a successful reunion.', category: 'Prevention', source: 'American Veterinary Medical Association', sourceUrl: 'https://ebusiness.avma.org/files/productdownloads/2011%20STWF%20English.pdf', sourceType: 'Veterinary guidance', takeaway: 'Keep visible ID and microchip registry information current before an emergency.' }
  ,{ title: 'Act quickly and involve local businesses', body: 'American Humane Society recommends starting immediately, searching the neighborhood, contacting shelters and animal control, and sharing photo signs in places such as veterinary offices, libraries, pet stores, and grocery stores.', category: 'Outreach', source: 'American Humane Society', sourceUrl: 'https://www.americanhumane.org/public-education/what-to-if-youve-lost-your-pet/', sourceType: 'Animal welfare guidance', takeaway: 'Begin outreach immediately and place clear notices where local people will actually see them.' }
]
const approach = [['Behavior first', 'Lifestyle, stress response, and outdoor experience change how far a search should begin from the escape point.'], ['Environment next', 'Only nearby hiding places reported by the owner are promoted in the ranking.'], ['Evidence over certainty', 'The platform turns published patterns into a checklist. It does not claim to know exactly where an individual cat is.']]

export function InfoPage({ type }: { type: 'resources' | 'approach' }) {
  const isResources = type === 'resources'
  const [page, setPage] = useState(1)
  const perPage = 6
  const pageCount = Math.ceil(resources.length / perPage)
  const visibleResources = resources.slice((page - 1) * perPage, page * perPage)
  if (!isResources) return <main className="page-shell py-14"><span className="pill"><Compass size={14} /> Our approach</span><h1 className="mt-4 max-w-2xl font-display text-5xl">Built around how cats actually behave.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-ink/65">The prediction engine uses published recovery patterns as a starting point and combines them with the details supplied for an individual search.</p><div className="mt-9 grid gap-4 md:grid-cols-3">{approach.map(([title, body]) => <article className="card p-5" key={title}><div className="grid size-10 place-items-center rounded-xl bg-[#eef4f0] text-moss"><PawPrint size={18} /></div><h2 className="mt-5 font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-ink/65">{body}</p></article>)}</div></main>
  return <main className="page-shell py-14"><span className="pill"><BookOpen size={14} /> Knowledge center</span><h1 className="mt-4 max-w-2xl font-display text-5xl">Search guidance with real sources.</h1><p className="mt-5 max-w-3xl text-sm leading-7 text-ink/65">These field guides summarize published research and established animal-welfare guidance. Each card links to its source so you can read the original material and make informed decisions.</p><div className="mt-7 flex items-center justify-between gap-4 border-b border-line pb-4"><p className="text-sm font-bold text-moss">{resources.length} source-backed guides</p><p className="text-xs font-bold text-ink/45">Page {page} of {pageCount}</p></div><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visibleResources.map((resource) => <article className="card flex flex-col p-5" key={resource.title}><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-[#fbefe9] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-[#9a563a]">{resource.category}</span><span className="text-right text-[10px] font-bold uppercase tracking-wide text-ink/40">{resource.sourceType}</span></div><h2 className="mt-5 font-bold">{resource.title}</h2><p className="mt-2 flex-1 text-sm leading-6 text-ink/65">{resource.body}</p><div className="mt-5 rounded-xl bg-[#eef4f0] p-3 text-xs leading-5 text-moss"><b>Field takeaway:</b> {resource.takeaway}</div><a href={resource.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-moss">Read source: {resource.source} <ArrowUpRight size={13} /></a></article>)}</div><Pagination page={page} count={pageCount} setPage={setPage} /><section className="mt-12 rounded-[1.5rem] bg-moss p-7 text-white"><div className="flex gap-3"><FileText className="shrink-0 text-sun" /><div><p className="eyebrow !text-sun">Source library</p><h2 className="mt-2 font-display text-3xl">Where this guidance comes from</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-white/75">The core distance and location findings come from Huang et al. (2018), a peer-reviewed missing-cat study. Behavior guidance is supplemented by Missing Animal Response Network, ASPCA, and Best Friends Animal Society. Treat every plan as a prioritized starting point and avoid entering unsafe structures or private spaces.</p></div></div></section></main>
}

function Pagination({ page, count, setPage }: { page: number; count: number; setPage: (page: number) => void }) {
  const change = (value: number) => { setPage(value); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <nav className="mt-8 flex items-center justify-center gap-2" aria-label="Knowledge center pages"><button className="btn-soft !px-3 !py-2 disabled:opacity-40" disabled={page === 1} onClick={() => change(page - 1)} aria-label="Previous page"><ArrowLeft size={15} /></button>{Array.from({ length: count }, (_, index) => index + 1).map((number) => <button key={number} onClick={() => change(number)} aria-current={number === page ? 'page' : undefined} className={`grid size-10 place-items-center rounded-full text-sm font-bold ${number === page ? 'bg-moss text-white' : 'border border-line bg-white text-moss hover:border-sage'}`}>{number}</button>)}<button className="btn-soft !px-3 !py-2 disabled:opacity-40" disabled={page === count} onClick={() => change(page + 1)} aria-label="Next page"><ArrowRight size={15} /></button></nav>
}
