import { useState } from 'react'
import { Bell, Check, KeyRound, LockKeyhole, MapPinned, Save } from 'lucide-react'

const defaults = { radius: '3', alerts: true, community: true, publicContact: false, apiUpdates: true, units: 'miles' }
const loadSettings = () => { const saved = localStorage.getItem('catwomanSettings'); return saved ? { ...defaults, ...JSON.parse(saved) } : defaults }

export function SettingsPage() {
  const [saved, setSaved] = useState(false)
  const [settings, setSettings] = useState(loadSettings)
  const update = (key: keyof typeof settings, value: string | boolean) => setSettings({ ...settings, [key]: value })
  function save() { localStorage.setItem('catwomanSettings', JSON.stringify(settings)); setSaved(true); window.setTimeout(() => setSaved(false), 1800) }
  return <main className="page-shell max-w-5xl py-12"><span className="pill">Your preferences</span><h1 className="section-title mt-4">A workspace that feels manageable.</h1><p className="helper">Tune how your search workspace, alerts, community posts, and developer updates behave.</p><div className="mt-8 grid gap-5">
    <SettingSection icon={<MapPinned />} title="Search area" body="Control your default nearby-sighting search preferences."><label className="mt-4 block text-sm font-bold">Default nearby radius<select className="input max-w-sm" value={settings.radius} onChange={(event) => update('radius', event.target.value)}>{['1', '3', '5', '10', '25'].map((value) => <option key={value} value={value}>{value} miles</option>)}</select></label></SettingSection>
    <SettingSection icon={<Bell />} title="Notifications" body="Choose the updates that should get your attention."><Toggle label="Nearby sighting alerts" body="Notify me when a community sighting is added near an active search." checked={settings.alerts} onChange={(value) => update('alerts', value)} /><Toggle label="Community update digest" body="Include search updates and safe-status posts." checked={settings.community} onChange={(value) => update('community', value)} /><Toggle label="CatWoman API updates" body="Receive developer-facing endpoint and schema updates." checked={settings.apiUpdates} onChange={(value) => update('apiUpdates', value)} /></SettingSection>
    <SettingSection icon={<LockKeyhole />} title="Privacy" body="Keep personal details under your control."><Toggle label="Show contact details on my posts" body="When enabled, your optional contact field may be displayed to nearby searchers." checked={settings.publicContact} onChange={(value) => update('publicContact', value)} /><p className="mt-4 text-xs leading-5 text-ink/55">Location and post content may be visible on the community sightings board. Avoid sharing private access details or unsafe instructions.</p></SettingSection>
    <SettingSection icon={<KeyRound />} title="Developer access" body="CatWoman API is available locally while public keys and scoped access are developed."><div className="mt-4 rounded-xl bg-[#f2eee7] p-4"><p className="text-xs font-bold uppercase tracking-wide text-peach">Local API base URL</p><code className="mt-2 block text-sm font-bold text-moss">http://localhost:4000/api</code></div></SettingSection>
  </div><button onClick={save} className="btn-primary mt-6">{saved ? <Check size={16} /> : <Save size={16} />}{saved ? 'Saved' : 'Save settings'}</button></main>
}
function SettingSection({ icon, title, body, children }: { icon: React.ReactNode; title: string; body: string; children: React.ReactNode }) { return <section className="card p-5 sm:p-6"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#fbefe9] text-peach">{icon}</span><div><h2 className="font-display text-2xl">{title}</h2><p className="mt-1 text-sm leading-6 text-ink/60">{body}</p></div></div>{children}</section> }
function Toggle({ label, body, checked, onChange }: { label: string; body: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="mt-4 flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-line p-3 hover:border-sage hover:bg-[#f8fbf9]"><span><b className="block text-sm">{label}</b><small className="mt-1 block leading-5 text-ink/55">{body}</small></span><input className="peer sr-only" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="relative h-6 w-11 shrink-0 rounded-full bg-line transition-colors peer-checked:bg-moss"><span className={`absolute top-1 size-4 rounded-full bg-white shadow transition-transform ${checked ? 'translate-x-6' : 'translate-x-1'}`} /></span></label> }
